# Template for deploying the Domain API to the devs environments. A new release is triggered when the build pipeline finishes

# This name will appear in the azure devops pipeline and will be the value of the BuildVersion (used in the Saas Admin monitor page)
name: $(SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)

pr: none

trigger: none

# This pipeline is triggered when the Build stage in the DomainApiBuild pipeline finishes
resources:
  pipelines:
  - pipeline: 'SDKBuild'
    source: 'Nfield SDK Build'
    trigger:
      branches:
        include: 
        - 'master'
        - '*/ci-*'
      stages:
      - Build # Run deploy-release pipeline when the build of SDK completes. If it only has one stage we could use "trigger: true" too.

pool:
  vmImage: windows-2022

stages:
- stage: GetResources
  jobs:
  - job: WaitForValidation
    displayName: Validate deploy
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        instructions: 'Please validate the deployment and resume'
        onTimeout: 'reject'

####################### DEPLOY ####################
- template: ./YmlTemplates/deploy.yml
  parameters:
    stageDependency: GetResources
    pipelineDependency: SDKBuild
    nugetRepository: nfield
    automaticPublis: true

- template: ./YmlTemplates/deploy.yml
  parameters:
    stageDependency: GetResources
    pipelineDependency: SDKBuild
    nugetRepository: 'nuget.org'
    automaticPublis: false
