name: $(SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)

pr: none

trigger: none

# This pipeline is triggered when the Build stage in the DomainApiBuild pipeline finishes
resources:
  pipelines:
  - pipeline: 'SDKBuild'
    source: 'Nfield SDK Build'
    trigger:
      branches:
        include: 
        - 'master'
        - '*/ci-*'
        - 'release/*'
      stages:
      - Build # Run deploy-release pipeline when the build of SDK completes. If it only has one stage we could use "trigger: true" too.

pool:
  vmImage: windows-2022

stages:
- template: AzureDevOps/SDK-and-Quota-pipelines/deploy-sdk-nuget.yml@NfieldTools 