name: $(SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)

pr: none

trigger: none

# This pipeline is triggered when the Build stage in the DomainApiBuild pipeline finishes
resources:
  pipelines:
  - pipeline: 'SDKBuild'
    source: 'Nfield SDK Build'
    trigger:
      branches:
        include: 
        - 'master'
        - '*/ci-*'
        - 'release/*'
      stages:
      - Build # Run deploy-release pipeline when the build of SDK completes. If it only has one stage we could use "trigger: true" too.


  repositories:
    - repository: NfieldTools
      type: github
      name: NIPOSoftwareBV/Nfield-Tools
      endpoint: NfieldToolsRepository
      ref: yellow/yml2nfieldtools # Defaults to master, to build with another version specify the ref here (e.g. 'refs/tags/2019-q1s01') If you want to build from a specific commit, first create a tag pointing to that commit, then pin to that tag.


pool:
  vmImage: windows-2022


stages:
- template: AzureDevOps/SDK-and-Quota-pipelines/deploy-sdk-nuget.yml@NfieldTools 